INSERT INTO CATEGORIES (NAME,DESCRIPTION)
    VALUES('Aviação','Produtos que te levem às Alturas')
/
INSERT INTO ITEM (NAME,DESCRIPTION,CATEGORY)
    VALUES('Propulsor', 'Um propulsor de 900J de força','Aviação');
/
INSERT INTO SIMPLE (ID,ITEM,USER,PRICE,DURATION,POST_DATE,QUANTITY)
SELECT COUNT(1),'Propulsor','Matheus',2000,30,7,2 FROM SIMPLE;
/
UPDATE SIMPLE 
SET CONCLUSION_DATE = 27
WHERE ID = 0