INSERT INTO AUCTION (ID,ITEM,CREATOR,DURATION,POST_DATE,MINIMUM_OFFER)
VALUES((SELECT COUNT(*) FROM AUCTION),'Propulsor',(SELECT REF(u) FROM USERS u WHERE u.NAME='Matheus'),30,2,50);
/
INSERT INTO AUCTION (ID,ITEM,CREATOR,DURATION,POST_DATE,MINIMUM_OFFER)
VALUES((SELECT COUNT(*) FROM AUCTION),'Prego',(SELECT REF(u) FROM USERS u WHERE u.NICKNAME='Jugurta'),15,3,28);
/
UPDATE AUCTION
SET CONCLUSION_DATE = 27
WHERE ID = (SELECT COUNT(*) FROM AUCTION)
