INSERT INTO AUCTION (ID,ITEM,CREATOR,DURATION,POST_DATE,MINIMUM_OFFER)
VALUES(
        (SELECT COUNT(*) FROM AUCTION),
        (SELECT REF(i) FROM ITEM i WHERE i.NAME='Propulsor'),
        (SELECT REF(u) FROM USERS u WHERE u.NAME='Matheus'),
        30,systimestamp,50
    );
/
INSERT INTO AUCTION (ID,ITEM,CREATOR,DURATION,POST_DATE,MINIMUM_OFFER)
VALUES(
        (SELECT COUNT(*) FROM AUCTION),
        (SELECT REF(i) FROM ITEM i WHERE i.NAME='Prego'),
        (SELECT REF(u) FROM USERS u WHERE u.NICKNAME='Jugurta'),
        15,systimestamp,28
    );
/
UPDATE AUCTION
SET CONCLUSION_DATE = systimestamp
WHERE ID = 0;