SELECT *
FROM SIMPLE s
WHERE s.ITEM.CATEGORY.NAME = 'Aviação';
/
SELECT *
FROM SIMPLE s
WHERE s.ITEM.CATEGORY.NAME = 'Jardinagem';
/
SELECT MAX(s.PRICE)
FROM SIMPLE s
WHERE s.ITEM.CATEGORY.NAME = 'Aviação';


